"use client";
import { useState } from "react";
import { ProductExplorer } from "./product-explorer";
import { UgcForm } from "./ugc-form";

const picks = [
  { rank: "01", title: "ストーリー重視", copy: "あらすじ・シリーズ情報・レビューの具体性を軸に探す", score: "編集部評価 4.7", tag: "初めての方へ" },
  { rank: "02", title: "短時間で選ぶ", copy: "発売日、価格帯、収録時間を同じ条件で比較", score: "情報鮮度 24h以内", tag: "比較しやすい" },
  { rank: "03", title: "新しい好みを発見", copy: "閲覧履歴ではなく、作品属性と審査済みUGCから探索", score: "UGC 128件", tag: "発見性" },
];

function SeoHub() { return <section className="section"><div className="sectionHead"><p className="eyebrow">GUIDES & CATEGORIES</p><h2>根拠から選ぶガイド</h2><p>検索意図ごとに、結論・比較軸・向く人を整理。</p></div><div className="cards"><article className="card"><b>START</b><h3>初めての選び方</h3><p>目的、時間、価格、雰囲気の順に確認。</p><footer><a href="/guides/hajimete">読む →</a></footer></article><article className="card"><b>TRUST</b><h3>ランキング計算方針</h3><p>推薦理由と広告報酬0%の考え方。</p><footer><a href="/guides/ranking-policy">読む →</a></footer></article><article className="card"><b>TASTE</b><h3>好み別カテゴリ</h3><p><a href="/categories/story">ストーリー</a>・<a href="/categories/costume">コスチューム</a>・<a href="/categories/romantic">ロマンチック</a>・<a href="/categories/long-form">長編</a></p><footer><a href="/guides/privacy">プライバシー方針 →</a></footer></article></div></section> }

function TasteMatch() {
  const options = ["物語重視", "ロマンチック", "コスチューム", "年上", "同年代", "主導されたい", "主導したい", "ソフト表現", "非日常", "長編"];
  const [selected, setSelected] = useState<string[]>([]);
  const toggle = (taste: string) => setSelected(current => current.includes(taste) ? current.filter(item => item !== taste) : [...current, taste]);
  return <section className="taste section" aria-labelledby="taste-title"><div className="sectionHead"><p className="eyebrow">PRIVATE TASTE MATCH</p><h2 id="taste-title">フェチ・好みから、<br />自分だけの棚へ。</h2><p>選択内容はサーバーへ送信せず、この画面内だけで照合します。</p></div><div className="tastePanel"><div><h3>気になる好みを選択</h3><p>複数選択できます。選んでいない好みを勝手に推測しません。</p><div className="tasteTags">{options.map(taste => <button type="button" key={taste} aria-pressed={selected.includes(taste)} onClick={() => toggle(taste)}>{taste}</button>)}</div><button className="clearTaste" type="button" onClick={() => setSelected([])}>選択をすべて消去</button></div><aside><span>あなたのマッチ条件</span>{selected.length ? <><strong>{selected.length}個の好みを選択中</strong><p>{selected.join(" ・ ")}</p><a href="#recommend-title">一致理由つきの候補を見る →</a></> : <><strong>まだ選択されていません</strong><p>タグを選ぶと、人気順では見つけにくい候補を優先します。</p></>}</aside></div><p className="privacyNote">プライバシー設計：アカウント紐付けなし・外部広告への送信なし・未選択属性の推測なし・ワンクリック消去。</p></section>;
}

export function SiteClient() {
  const [adult, setAdult] = useState(false);
  const [sent, setSent] = useState(false);
  return <main>{!adult && <div className="gateOverlay" role="dialog" aria-modal="true" aria-labelledby="age-title"><div className="gateCard"><p className="eyebrow">AGE CONFIRMATION</p><h1 id="age-title">ここから先は<br />成人向け情報を含みます。</h1><p>18歳未満の方は利用できません。本文は検索可能なテキストとして保持し、センシティブ画像は確認前に表示しません。</p><button onClick={() => setAdult(true)}>18歳以上です</button><a href="https://www.dmm.com/">退出する</a><a href="/policies/editorial">編集・安全方針を確認</a></div></div>}<TasteMatch /><ProductExplorer /><SeoHub /><UgcForm />
    <div className="notice">PR・広告を含みます　｜　最終更新 2026.07.15　｜　情報源：DMM Affiliate API v3 / 各公式ページ</div>
    <header><a className="logo" href="#top">比較<i>LAB</i></a><nav><a href="#find">見つける</a><a href="#method">評価方針</a><a href="#voices">みんなの声</a><a href="#sdk">APIガイド</a></nav></header>
    <section className="hero" id="top"><div><p className="eyebrow">CHOOSE WITH CONTEXT, NOT HYPE.</p><h1>作品選びを、<br /><em>透明</em>に。</h1><p className="lead">広告だから推す、を終わらせる。出典・更新日・評価軸・ユーザーの声を分けて示す、比較と発見のガイドです。</p><div className="actions"><a className="primary" href="#find">自分に合う探し方を見る</a><a href="#method">編集方針を読む →</a></div></div><aside><span>編集部の約束</span><strong>報酬額だけで<br />順位を決めません。</strong><p>公式データとUGCを混同せず、広告リンクには明確な表示を付けます。</p></aside></section>
    <section className="section" id="find"><div className="sectionHead"><p className="eyebrow">DISCOVERY PATHS</p><h2>今日の選び方</h2><p>作品名を並べる前に、選ぶ基準をつくる。</p></div><div className="cards">{picks.map(p => <article className="card" key={p.rank}><span className="rank">{p.rank}</span><b>{p.tag}</b><h3>{p.title}</h3><p>{p.copy}</p><footer>{p.score}<button aria-label={`${p.title}で探す`}>→</button></footer></article>)}</div><p className="affiliate">リンク先で購入が成立した場合、当サイトが報酬を受け取ることがあります。価格・配信状況は必ず公式サイトでご確認ください。</p></section>
    <section className="recommend section" aria-labelledby="recommend-title"><div className="sectionHead"><p className="eyebrow">EXPLAINABLE RECOMMENDATION</p><h2 id="recommend-title">これを見た人の、<br />次の選択。</h2><p>閲覧数だけでなく「なぜ合うか」まで表示します。</p></div><div className="recommendGrid"><article className="seed"><span>いま見ている条件</span><h3>物語性 × 60分以上 × 高評価</h3><p>センシティブ画像を使わず、作品属性と匿名の集計データだけで比較しています。</p><div className="chips"><b>物語性</b><b>長編</b><b>新着除外</b></div></article><div className="nextPicks"><article><span>一致度 92%</span><h3>同じ物語性で選ばれた作品</h3><p><strong>推薦理由：</strong>閲覧者の68%が「ストーリー」を役立つ評価軸に選択。</p><a href="#sdk" rel="sponsored nofollow">公式情報を確認して見る →</a></article><article><span>意外性 74%</span><h3>好みを少し広げる関連作品</h3><p><strong>推薦理由：</strong>長編を見た人が次に選んだ別カテゴリ。人気順だけでは出ない候補です。</p><a href="#sdk" rel="sponsored nofollow">比較条件を確認する →</a></article></div></div><div className="trustRow"><span>匿名・端末内シグナル</span><span>広告報酬を推薦スコアから除外</span><span>推薦理由を常時表示</span><span>「興味なし」で調整可能</span></div></section>
    <section className="method" id="method"><div><p className="eyebrow">EDITORIAL POLICY</p><h2>AIにも、人にも、<br />根拠が見える記事へ。</h2></div><ol><li><span>01</span><strong>一次情報を優先</strong><p>API取得日時と公式ページを明示。推測と事実を分離します。</p></li><li><span>02</span><strong>比較軸を固定</strong><p>価格、発売日、情報量、UGCの具体性を同じ尺度で評価します。</p></li><li><span>03</span><strong>更新履歴を残す</strong><p>重要な変更は記事内に記録し、古い情報を放置しません。</p></li></ol></section>
    <section className="voices section" id="voices"><div className="sectionHead"><p className="eyebrow">MODERATED UGC</p><h2>みんなの「選びやすかった」</h2><p>満足度だけでなく、どんな人の判断に役立ったかを集めます。</p></div><div className="quotes"><blockquote>「評価の理由が短く整理されていて、公式ページで確認してから決められた。」<cite>30代・ストーリー重視　／　審査済み</cite></blockquote><blockquote>「画像を表示しなくても比較できるので、落ち着いて探せた。」<cite>40代・プライバシー重視　／　審査済み</cite></blockquote></div>{sent ? <div className="thanks">投稿ありがとうございます。編集部の審査後、個人を特定できない形で掲載します。</div> : <form onSubmit={e => { e.preventDefault(); setSent(true); }}><label>どんな点が選択に役立ちましたか？<textarea required minLength={20} maxLength={400} placeholder="具体的な判断材料を20〜400文字で（個人情報・作品の詳細描写は入力しないでください）" /></label><div><label>満足度<select defaultValue=""><option value="" disabled>選択</option><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><button type="submit">審査へ送る</button></div><small>投稿は即時公開されません。誹謗中傷、個人情報、権利侵害、スパム、具体的すぎる性的表現は掲載対象外です。</small></form>}</section>
    <section className="sdk" id="sdk"><p className="eyebrow">FOR DEVELOPERS</p><h2>DMM Affiliate API v3<br />安全な実装チェック</h2><div className="code"><code>GET /api/items?keyword=...</code><p>API ID・アフィリエイトIDはサーバー環境変数で管理</p><p>入力値を許可リストで検証し、取得結果を短時間キャッシュ</p><p>エラー時は空配列へフォールバックし、秘密情報をログに残さない</p><p>affiliateURLのみをPRリンクとして利用し、rel="sponsored"を付与</p></div><p className="source">参照先：DMM Affiliate API v3 Affiliate SDK（地域により閲覧制限あり）。実運用前に管理画面で最新の利用条件とレスポンス仕様を必ず確認してください。</p></section>
    <section className="faq section"><h2>よくある質問</h2><details><summary>ランキングはどのように作成していますか？</summary><p>公式APIの公開情報、情報の鮮度、価格、審査済みUGCを分離して表示し、広告報酬だけで順位を決めません。</p></details><details><summary>口コミはすべて掲載されますか？</summary><p>いいえ。投稿ポリシーに基づく人手または自動審査を通過した内容だけを掲載します。</p></details></section>
    <footer className="siteFooter"><div className="logo">比較<i>LAB</i></div><p>作品選びに、透明なものさしを。</p><nav><a href="#method">編集方針</a><a href="#voices">投稿ポリシー</a><a href="#sdk">APIガイド</a></nav><small>© 2026 比較LAB (hikakulab.jp). FANZA・DUGA・DLsite等、記載の各ASP名は各権利者の商標です。本サイトはいずれの提供元とも関係のない非公式の比較メディアです。</small></footer>
  </main>;
}
